<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Pane</AssemblyName>
    <Product>Pane</Product>
    <Title>Pane</Title>
    <Description>Pane</Description>
    <FileDescription>Pane</FileDescription>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>false</EnableMsixTooling>
    <WindowsPackageType>None</WindowsPackageType>
    <AppxPackageSigningEnabled>false</AppxPackageSigningEnabled>
    <GenerateAppInstallerFile>false</GenerateAppInstallerFile>
    <WindowsAppSDKSelfContained>false</WindowsAppSDKSelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Platforms>x64</Platforms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\Pane.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Assets\Pane.ico" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.WindowsDesktop.App.WindowsForms" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.7.250606001" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
    <ProjectReference Include="../Wallflow.Core/Wallflow.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\*.png" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
